### ISSUE TITLE
Logic Analyser

### ISSUE THREAD

**Issue by romcoca** [stefan73/BetterTeslaChargeportOpener#1]
Hello,
I think you are using a DSLogic with DSView to analyse the signal.
I did the same but I just want to know how you decode the signal and display hexa value ?
Your code is working with my model 3 2021.
Regards

**Comment by stefan73** [comment]
Hi romcoca,
the analysis was done with a Saleae Logic Analyzer from a friend. The SW package allows to decode Manchester Code and display the value. Not sure if DSView can do the same thing.
Great that the code works for you.

**Comment by jLynx** [comment]
Can I ask how you were able to get the output in Saleae Logic Analyzer?
I am not able to get the code to work for me, but I have a Tesla with a gen 3 wall charger to record and a HackRF that already successfully can replay the the recorded RF transmission from the charger handle. I would like to decode this using Saleae Logic Analyzer but I am not quite sure how to set that up. Any suggestions?

**Comment by stefan73** [comment]
The sampling circuit was super simple. I used a SRX882 receiver and powered it with 5V. Connected the data line and GND to the Saleae Analyzer and sampled with a very high frequency. Placed the SRX882 next to the Tesla UMC. That's all.
But I need to voice a doubt. It does not sound very reasonable to me that Tesla changed the RF protocol. That would drive them into issues with their Superchargers which need to work with all cars. Thus a question: Where are you located? - The circuit described works in the EU and uses 433MHz. E.g. in the US 315MHz are used. So you might need to check, if things operate on the right frequency. HackRF should show where you are in frequency space.
You also need to use a reasonably good transmitter. The cheap ones usually do not work (e.g. FS1000A).

**Comment by jLynx** [comment]
@jLynx I am in NZ and we use 433. You can see my recording here https://github.com/eried/portapack-mayhem/blob/next/sdcard/SAMPLES/TeslaChargePort_EU_AU.C16.  (433.95)

I am testing using a CC1101 and it doesn't seem to open the charge port using your code. So I am not entirely sure what is going wrong here. Free free to message me on Discord if you would like to discuss further jLynx#7987

I can see the wave form looks different to the once generated by this sketch. I am interested to hear your feedback
